version: "1.0"
type: component
data:
  name: omv-services-restic-settings-form-page
  type: formPage
  config:
    request:
      service: Restic
      get:
        method: getSettings
    fields:
      - type: textInput
        name: version
        label: _("Version")
        value: ""
        hint: _("The current version number of Restic.")
    buttons:
      - text: _("Update Restic")
        icon: mdi:update
        execute:
          type: request
          request:
            service: Restic
            method: updateRestic
            progressMessage: _("Checking for Restic updates.")
            successUrl: /services/restic
      - template: cancel
        execute:
          type: url
          url: /services/restic
